name: deployment-of-python-app
on:
  pull_request:
    paths:
      - '**.py'
jobs:
  build:
    name: Deploy python app
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "This has been triggered ${{ github.event_name }} event."
      - run: echo "This job is running on ${{ runner.os }} server hosted on github."
      
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install pylint
          pip install pycodestyle
      - name: Unit testing
        run: |
          python3 -m doctest factorial.py
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Style with pycodestyle
        run: |
          pycodestyle *.py
      - name: Build container
        run: |
          echo "Building a container image..."
          sleep 5
      - name: Deploy to cluster
        run: |
          echo "Deploying to cluster"
          sleep 5
          echo "Container has been deployed!"
      - run: echo "This job's status is ${{ job.status }}."
